#pragma once

#define NETWORK_IDENTITY_HOSTNAME "kvm"
#define NETWORK_IDENTITY_SERVICE_NAME "Serialite"
#define NETWORK_IDENTITY_HTTP_SERVICE "_http"
#define NETWORK_IDENTITY_HTTPS_SERVICE "_https"
#define NETWORK_IDENTITY_LOCAL_URL "http://192.168.4.1"
#define NETWORK_IDENTITY_LOCAL_HTTPS_URL "https://kvm.local"
